spring.application.name=api

app.books.gb.base-url=https://www.googleapis.com/books/v1/
app.books.gb.connect-timeout-ms=1000
app.books.gb.read-timeout-ms=2000
app.books.gb.retries=2
app.books.gb.api-key=${APP_BOOKS_GB_API_KEY}
java.awt.headless=true

logging.level.ovh=DEBUG

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.data.jpa.repository.query=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG