logging.level.ovh=DEBUG

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.data.jpa.repository.query=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
